name: Deploy Angular to Cloud Run

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'feat/*'

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: us-central1
      REPO_NAME: ccp-web-repo

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      # Instalar Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      # Ejecutar pruebas unitarias con cobertura
      - name: Run Unit Tests with Coverage
        run: npm run test:coverage

      # Iniciar servidor en segundo plano para pruebas e2e
      - name: Start Angular server for e2e tests
        run: |
          npm run start &
          echo "Started Angular server, waiting for it to be ready..."
          # Esperar a que el servidor esté listo (ajustar según necesidad)
          sleep 30

      # Ejecutar pruebas e2e
      - name: Run E2E Tests with Playwright
        run: npm run e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Set environment variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
            echo "SERVICE=ccp-web-prod" >> $GITHUB_ENV
            echo "IMAGE_NAME=ccp-web-prod" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
            echo "SERVICE=ccp-web-dev" >> $GITHUB_ENV
            echo "IMAGE_NAME=ccp-web-dev" >> $GITHUB_ENV
          fi

      - name: Build Angular app for Production
        if: github.ref == 'refs/heads/main'
        run: npm run build -- --configuration=production

      - name: Build Angular app for Development
        if: github.ref != 'refs/heads/main'
        run: npm run build

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker image for Production
        if: github.ref == 'refs/heads/main'
        run: |
          docker build \
            --build-arg BUILD_ENV=production \
            --build-arg ENCRYPTION_KEY="${{ secrets.ENCRYPTION_KEY }}" \
            -t us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker push us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Build and Push Docker image for Development
        if: github.ref != 'refs/heads/main'
        run: |
          docker build \
            --build-arg BUILD_ENV=development \
            --build-arg ENCRYPTION_KEY="${{ secrets.ENCRYPTION_KEY }}" \
            -t us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker push us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE }} \
            --image us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars="ENVIRONMENT=${{ env.ENVIRONMENT }}"
